@startuml Docotlight
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #EEF
  BorderColor #333
  ArrowColor #333
}

actor "Patient" as patient
actor "Staff" as staff

usecase "Prendre un rendez-vous" as UC1
usecase "Modifier un rendez-vous" as UC2
usecase "Annuler un rendez-vous" as UC3
usecase "Consulter ses rendez-vous" as UC4
usecase "Gérer les rendez-vous" as UC5
usecase "Consulter RDV par patient" as UC6
usecase "Consulter RDV par médecin" as UC7
usecase "Consulter RDV par date" as UC8
usecase "Gérer disponibilités" as UC9
usecase "Gérer disponibilités services" as UC10
usecase "Créer / gérer services" as UC11
usecase "Gérer les utilisateurs" as UC12
usecase "Consulter journaux (Audit Log)" as UC13
usecase "Consulter actualités" as UC14
usecase "Publier actualités" as UC15

' Associations
patient --> UC1
patient --> UC2
patient --> UC3
patient --> UC4
patient --> UC14

staff --> UC5
staff --> UC6
staff --> UC7
staff --> UC8
staff --> UC9
staff --> UC10
staff --> UC11
staff --> UC12
staff --> UC13
staff --> UC15

@enduml
