@startuml Docotlight
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #EEF
  BorderColor #333
  ArrowColor #333
}

actor "Patient" as patient
actor "Secrétaire" as secretaire
actor "Médecin" as medecin
actor "Admin" as admin

usecase "Prendre son rendez-vous" as UC1
usecase "Modifier ses rendez-vous" as UC2
usecase "Annuler ses rendez-vous" as UC3
usecase "Consulter ses rendez-vous" as UC4
usecase "Gérer les rendez-vous" as UC5
usecase "Consulter RDV par patient" as UC6
usecase "Consulter RDV par médecin" as UC7
usecase "Consulter RDV par date" as UC8
usecase "Gérer disponibilités médecins" as UC9
usecase "Gérer disponibilités services" as UC10
usecase "Gérer services" as UC11
usecase "Gérer les utilisateurs" as UC12
usecase "Consulter journaux (Audit Log)" as UC13
usecase "Consulter actualités" as UC14
usecase "Publier actualités" as UC15
usecase "Consulter RDV par Service" as UC16
usecase "Consulter services" as UC17
usecase "Gérer son profil" as UC18
usecase "Gérer fermetures" as UC19

' Associations
patient --> UC1
patient --> UC2
patient --> UC3
patient --> UC4
patient --> UC14
patient --> UC17
patient --> UC18

medecin --> UC9
medecin --> UC17
medecin --> UC14
medecin --> UC4

secretaire --> UC5
secretaire --> UC6
secretaire --> UC7
secretaire --> UC8
secretaire --> UC10
secretaire --> UC16
secretaire --> UC11
secretaire --> UC19

admin --> UC10
admin --> UC12
admin --> UC7
admin --> UC16
admin --> UC11
admin --> UC12
admin --> UC13
admin --> UC15
admin --> UC18

@enduml
