name: Deploy to alwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ALWAYSDATA_HOST }}
          username: ${{ secrets.ALWAYSDATA_USER }}
          key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
          script: |
            cd ~/www/doctolight
            git fetch origin main
            git reset --hard origin/main
