name: Deploy to AlwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug DNS resolution
        run: |
          echo "Test DNS sur ssh-baptistev59.alwaysdata.net"
          ping -c 3 ssh-baptistev59.alwaysdata.net || true
          nslookup ssh-baptistev59.alwaysdata.net || true

      - name: Deploy to alwaysData via SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/baptistev59/www/doctotlight/
          remote_host: 185.31.41.85
          remote_port: 22
          remote_user: ${{ secrets.ALWAYSDATA_USER }}
          remote_key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
