name: Deploy to AlwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug DNS resolution
        run: |
          echo "Test DNS sur ssh-baptistev59.alwaysdata.net"
          ping -c 3 ssh-baptistev59.alwaysdata.net || true
          nslookup ssh-baptistev59.alwaysdata.net || true

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ALWAYSDATA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 185.31.41.85 >> ~/.ssh/known_hosts

      - name: Deploy to alwaysData via rsync
        run: |
          rsync -avzr --delete \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude 'tests/' \
          --exclude 'README.md' \
          ./ ${{ secrets.ALWAYSDATA_USER }}@185.31.41.85:/home/baptistev59/www/doctolight/
